import type { MuscleKey } from './muscles'

export type Equipment = 'sztanga' | 'hantle' | 'maszyna' | 'wyciąg' | 'własna_waga'
export type ExerciseType = 'compound' | 'isolation'
export type Difficulty = 'beginner' | 'intermediate' | 'advanced'
export type MovementPattern =
  | 'horizontal_push' | 'vertical_push'
  | 'horizontal_pull' | 'vertical_pull'
  | 'squat' | 'hinge' | 'lunge'
  | 'calf' | 'core'
  | 'elbow_flexion' | 'elbow_extension'
  | 'shoulder_isolation'

export interface ExerciseEntry {
  id: string
  name: string
  aliases: string[]
  primaryMuscle: string
  muscleHead: MuscleKey
  equipment: Equipment
  exerciseType: ExerciseType
  movementPattern: MovementPattern
  difficulty: Difficulty
  isUnilateral: boolean
  defaultSets: number
  defaultReps: string
  tip: string
}

// ---------------------------------------------------------------------------
//  PUSH — klatka piersiowa, barki przednie/boczne, triceps
// ---------------------------------------------------------------------------

export const PUSH_EXERCISES: ExerciseEntry[] = [

  // ===================== KLATKA GÓRNA (chest_upper) =====================

  {
    id: 'wyciskanie-sztangi-na-lawce-skosnej',
    name: 'Wyciskanie sztangi na ławce skośnej',
    aliases: ['incline bench press', 'incline barbell press', 'incline barbell bench press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '8-12',
    tip: 'Ławka 30-45°. Łopatki ściągnięte, sztanga nad obojczykami.',
  },
  {
    id: 'wyciskanie-hantli-na-lawce-skosnej',
    name: 'Wyciskanie hantli na ławce skośnej',
    aliases: ['incline dumbbell press', 'incline dumbbell bench press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '8-12',
    tip: 'Ławka 30-45°. Hantle nad linią obojczyków, łokcie 45° od tułowia.',
  },
  {
    id: 'wyciskanie-na-maszynie-na-skosie',
    name: 'Wyciskanie na maszynie na skosie',
    aliases: ['incline machine press', 'incline chest press machine'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Ustaw siedzisko tak, by uchwyty były na wysokości obojczyków.',
  },
  {
    id: 'rozpietki-hantlami-na-lawce-skosnej',
    name: 'Rozpiętki hantlami na ławce skośnej',
    aliases: ['incline dumbbell fly', 'incline dumbbell flyes', 'incline flyes'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Lekki łuk w łokciach. Rozciągaj do uczucia napięcia, nie bólu.',
  },
  {
    id: 'krzyzowanie-linek-dolne',
    name: 'Krzyżowanie linek dolne',
    aliases: ['low cable crossover', 'low to high cable fly', 'cable crossover dolny'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Uchwyty z dołu do góry. Ruch po łuku, złącz ręce nad klatką.',
  },
  {
    id: 'pompki-z-nogami-na-podwyzszeniu',
    name: 'Pompki z nogami na podwyższeniu',
    aliases: ['decline push up', 'decline push-up', 'decline pushup', 'feet elevated push up'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Stopy na ławce/skrzyni. Im wyżej nogi, tym więcej akcentu na górną klatkę.',
  },

  // ===================== KLATKA ŚRODKOWA (chest_middle) =====================

  {
    id: 'wyciskanie-sztangi-na-lawce-poziomej',
    name: 'Wyciskanie sztangi na ławce poziomej',
    aliases: ['bench press', 'flat bench press', 'barbell bench press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '6-10',
    tip: 'Łopatki ściągnij i wciśnij w ławkę. Stopy płasko na podłodze.',
  },
  {
    id: 'wyciskanie-hantli-na-lawce-poziomej',
    name: 'Wyciskanie hantli na ławce poziomej',
    aliases: ['dumbbell bench press', 'flat dumbbell press', 'dumbbell press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '8-12',
    tip: 'Większy zakres ruchu niż sztanga. Łokcie 45° od tułowia.',
  },
  {
    id: 'wyciskanie-na-maszynie',
    name: 'Wyciskanie na maszynie',
    aliases: ['chest press', 'machine chest press', 'chest press na maszynie'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Uchwyty na wysokości brodawek. Wyciskaj bez odchylania pleców.',
  },
  {
    id: 'pompki-klasyczne',
    name: 'Pompki klasyczne',
    aliases: ['push up', 'push-up', 'push ups', 'push-ups', 'pushup'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-20',
    tip: 'Ciało jak deska. Łokcie 45° od tułowia, klatka do podłogi.',
  },
  {
    id: 'rozpietki-hantlami-na-lawce-poziomej',
    name: 'Rozpiętki hantlami na ławce poziomej',
    aliases: ['dumbbell fly', 'dumbbell flyes', 'chest fly', 'chest flyes', 'flyes'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Lekki łuk w łokciach przez cały ruch. Czuj rozciągnięcie klatki.',
  },
  {
    id: 'rozpietki-na-maszynie',
    name: 'Rozpiętki na maszynie',
    aliases: ['pec deck', 'peck deck', 'butterfly', 'pec fly machine'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Złącz ramiona powoli przed klatką. 1-2s pauza w skurczu.',
  },
  {
    id: 'krzyzowanie-linek',
    name: 'Krzyżowanie linek',
    aliases: ['cable crossover', 'cable fly', 'cable flyes', 'cable chest fly'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Lekki wychył tułowia. Krzyżuj ręce na dole dla pełnego skurczu.',
  },

  // ===================== KLATKA DOLNA (chest_lower) =====================

  {
    id: 'wyciskanie-sztangi-na-lawce-ujemnej',
    name: 'Wyciskanie sztangi na ławce ujemnej',
    aliases: ['decline bench press', 'decline barbell press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_lower',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Ławka ujemna 15-30°. Sztanga na dolną część klatki.',
  },
  {
    id: 'wyciskanie-hantli-na-lawce-ujemnej',
    name: 'Wyciskanie hantli na ławce ujemnej',
    aliases: ['decline dumbbell press', 'decline dumbbell bench press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_lower',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Kontroluj hantle — na ławce ujemnej trudniej stabilizować.',
  },
  {
    id: 'pompki-na-poreczach',
    name: 'Pompki na poręczach',
    aliases: ['dips', 'chest dips', 'parallel bar dips'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_lower',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Wychyl tułów do przodu dla akcentu na klatkę. Łokcie lekko na boki.',
  },
  {
    id: 'krzyzowanie-linek-gorne',
    name: 'Krzyżowanie linek górne',
    aliases: ['high cable crossover', 'high to low cable fly', 'cable crossover górny'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_lower',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Uchwyty z góry na dół. Złącz ręce na poziomie bioder.',
  },

  // ===================== BARKI PRZEDNIE (shoulder_front) =====================

  {
    id: 'wyciskanie-sztangi-nad-glowe',
    name: 'Wyciskanie sztangi nad głowę',
    aliases: ['overhead press', 'ohp', 'military press', 'wyciskanie żołnierskie', 'standing barbell press', 'barbell overhead press'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '6-10',
    tip: 'Napnij pośladki i brzuch. Głowa lekko do przodu gdy sztanga przechodzi.',
  },
  {
    id: 'wyciskanie-hantli-nad-glowe',
    name: 'Wyciskanie hantli nad głowę',
    aliases: ['dumbbell shoulder press', 'dumbbell overhead press', 'shoulder press'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '8-12',
    tip: 'Można stojąc lub siedząc. Wyciskaj hantle po łuku ku środkowi.',
  },
  {
    id: 'wyciskanie-hantli-siedzac',
    name: 'Wyciskanie hantli siedząc',
    aliases: ['seated dumbbell press', 'seated shoulder press', 'seated dumbbell shoulder press'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '8-12',
    tip: 'Oparcie ławki 85-90°. Łokcie pod hantlami przez cały ruch.',
  },
  {
    id: 'wyciskanie-arnolda',
    name: 'Wyciskanie Arnolda',
    aliases: ['arnold press', 'arnold dumbbell press'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Start z dłońmi do siebie. Obracaj podczas wyciskania — ruch płynny.',
  },
  {
    id: 'wyciskanie-nad-glowa-na-maszynie',
    name: 'Wyciskanie nad głowę na maszynie',
    aliases: ['machine shoulder press', 'shoulder press machine'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Siedzisko ustaw tak, by uchwyty startowały na wysokości uszu.',
  },
  {
    id: 'wznosy-hantli-przodem',
    name: 'Wznosy hantli przodem',
    aliases: ['front raise', 'dumbbell front raise', 'front dumbbell raise'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Unoś do poziomu oczu. Nie rozbujaj tułowiem — lekki ciężar.',
  },
  {
    id: 'wznosy-przodem-na-wyciagu',
    name: 'Wznosy przodem na wyciągu',
    aliases: ['cable front raise', 'front cable raise'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Stały opór wyciągu przez cały zakres. Unoś do poziomu barków.',
  },

  // ===================== BARKI BOCZNE (shoulder_side) =====================

  {
    id: 'wznosy-hantli-bokiem',
    name: 'Wznosy hantli bokiem',
    aliases: ['lateral raise', 'dumbbell lateral raise', 'side lateral raise', 'side raise'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_side',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Unoś do poziomu barków. Lekki łuk w łokciach, małe palce wyżej.',
  },
  {
    id: 'wznosy-hantli-bokiem-siedzac',
    name: 'Wznosy hantli bokiem siedząc',
    aliases: ['seated lateral raise', 'seated dumbbell lateral raise'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_side',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Siedzenie eliminuje rozpęd. Skup się na kontrolowanym ruchu.',
  },
  {
    id: 'wznosy-bokiem-na-wyciagu',
    name: 'Wznosy bokiem na wyciągu',
    aliases: ['cable lateral raise', 'single arm cable lateral raise'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_side',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'intermediate',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Wyciąg za plecami lub z boku. Stały opór przez cały zakres ruchu.',
  },
  {
    id: 'wznosy-bokiem-na-maszynie',
    name: 'Wznosy bokiem na maszynie',
    aliases: ['machine lateral raise', 'lateral raise machine', 'lateral raise na maszynie'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_side',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Maszyna stabilizuje tor — skup się na skurczu barków bocznych.',
  },
  {
    id: 'wioslowanie-sztangi-pod-brode',
    name: 'Wiosłowanie sztangi pod brodę',
    aliases: ['upright row', 'barbell upright row'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_side',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Szeroki chwyt dla barków bocznych. Ciągnij łokcie w górę, nie nadgarstki.',
  },

  // ===================== TRICEPS — GŁOWA DŁUGA (triceps_long) =====================

  {
    id: 'francuskie-wyciskanie-sztangi',
    name: 'Francuskie wyciskanie sztangi',
    aliases: ['skull crusher', 'skullcrusher', 'skull crushers', 'lying triceps extension', 'french press'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'sztanga',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Opuszczaj za głowę (nie na czoło) dla pełnego rozciągnięcia długiej głowy.',
  },
  {
    id: 'francuskie-wyciskanie-sztanga-ez',
    name: 'Francuskie wyciskanie ze sztangą EZ',
    aliases: ['ez bar skull crusher', 'ez bar french press', 'ez skull crusher'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'sztanga',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Sztanga EZ odciąża nadgarstki. Łokcie stale — ruch tylko w łokciach.',
  },
  {
    id: 'francuskie-wyciskanie-hantli',
    name: 'Francuskie wyciskanie hantli',
    aliases: ['dumbbell skull crusher', 'lying dumbbell triceps extension'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Neutralny chwyt hantli. Opuszczaj obok głowy, nie na twarz.',
  },
  {
    id: 'wyprosty-triceps-nad-glowa-na-wyciagu',
    name: 'Wyprosty triceps nad głowę na wyciągu',
    aliases: ['cable overhead triceps extension', 'overhead cable extension', 'overhead triceps extension'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Tyłem do wyciągu. Łokcie przy uszach, prostuj w pełni nad głową.',
  },
  {
    id: 'wyprosty-triceps-nad-glowa-z-hantla',
    name: 'Wyprosty triceps nad głowę z hantlą',
    aliases: ['overhead dumbbell triceps extension', 'dumbbell overhead extension', 'overhead tricep extension'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Chwyć hantlę oburącz za talerz. Opuszczaj za głowę, łokcie przy uszach.',
  },
  {
    id: 'wyprosty-triceps-nad-glowa-jednorecz',
    name: 'Wyprosty triceps nad głowę jednorącz',
    aliases: ['single arm overhead triceps extension', 'one arm dumbbell extension'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Drugą ręką stabilizuj łokieć. Pełne rozciągnięcie na dole.',
  },

  // ===================== TRICEPS — GŁOWA BOCZNA (triceps_lat) =====================

  {
    id: 'wyprosty-triceps-na-wyciagu',
    name: 'Wyprosty triceps na wyciągu',
    aliases: ['triceps pushdown', 'tricep pushdown', 'cable pushdown', 'pushdown', 'cable triceps pushdown'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_lat',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Łokcie przyklejone do tułowia. Prostuj w pełni na dole, 1s pauza.',
  },
  {
    id: 'pushdown-z-lina',
    name: 'Pushdown z liną',
    aliases: ['rope pushdown', 'triceps rope pushdown', 'rope triceps pushdown'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_lat',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Rozciągaj linę na dole — rozsuń końce na boki dla pełnego skurczu.',
  },
  {
    id: 'wyprosty-triceps-na-wyciagu-jednorecz',
    name: 'Wyprosty triceps na wyciągu jednorącz',
    aliases: ['single arm pushdown', 'one arm cable pushdown', 'single arm triceps pushdown'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_lat',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Pozwala wyczuć pracę tricepsu każdą ręką osobno. Pełne wyprostowanie.',
  },
  {
    id: 'wyprosty-hantla-w-opadzie',
    name: 'Wyprosty hantla w opadzie',
    aliases: ['tricep kickback', 'kickback', 'dumbbell kickback', 'triceps kickback'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_lat',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Tułów równolegle do podłogi. Ramię nieruchomo — ruch tylko w łokciu.',
  },

  // ===================== TRICEPS — GŁOWA PRZYŚRODKOWA (triceps_med) =====================

  {
    id: 'wyciskanie-waskim-chwytem',
    name: 'Wyciskanie wąskim chwytem',
    aliases: ['close grip bench press', 'close grip press', 'narrow grip bench press'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_med',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Chwyt na szerokość barków. Łokcie blisko tułowia, nie rozchylaj.',
  },
  {
    id: 'pompki-diamentowe',
    name: 'Pompki diamentowe',
    aliases: ['diamond push up', 'diamond push-up', 'diamond pushup', 'close grip push up'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_med',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-15',
    tip: 'Dłonie złączone w diament pod klatką. Łokcie przy tułowiu.',
  },
]

// ---------------------------------------------------------------------------
//  Helpers
// ---------------------------------------------------------------------------

const _pushById = new Map<string, ExerciseEntry>()
const _pushByName = new Map<string, ExerciseEntry>()
const _pushByAlias = new Map<string, ExerciseEntry>()

for (const ex of PUSH_EXERCISES) {
  _pushById.set(ex.id, ex)
  _pushByName.set(ex.name.toLowerCase(), ex)
  for (const alias of ex.aliases) {
    _pushByAlias.set(alias.toLowerCase(), ex)
  }
}

export function findExerciseById(id: string): ExerciseEntry | undefined {
  return _pushById.get(id)
}

export function findExerciseByName(name: string): ExerciseEntry | undefined {
  const lower = name.toLowerCase().trim()
  return _pushByName.get(lower) || _pushByAlias.get(lower)
}

export function getExercisesForMuscle(muscleHead: MuscleKey): ExerciseEntry[] {
  return PUSH_EXERCISES.filter(e => e.muscleHead === muscleHead)
}

export function getExercisesByEquipment(equipment: Equipment): ExerciseEntry[] {
  return PUSH_EXERCISES.filter(e => e.equipment === equipment)
}

export function getCompoundExercises(): ExerciseEntry[] {
  return PUSH_EXERCISES.filter(e => e.exerciseType === 'compound')
}

export function getIsolationExercises(): ExerciseEntry[] {
  return PUSH_EXERCISES.filter(e => e.exerciseType === 'isolation')
}
