import type { MuscleKey } from './muscles'

export type Equipment = 'sztanga' | 'hantle' | 'maszyna' | 'wyciąg' | 'własna_waga'
export type ExerciseType = 'compound' | 'isolation'
export type Difficulty = 'beginner' | 'intermediate' | 'advanced'
export type MovementPattern =
  | 'horizontal_push' | 'vertical_push'
  | 'horizontal_pull' | 'vertical_pull'
  | 'squat' | 'hinge' | 'lunge'
  | 'calf' | 'core'
  | 'elbow_flexion' | 'elbow_extension'
  | 'shoulder_isolation'

export interface ExerciseEntry {
  id: string
  name: string
  aliases: string[]
  primaryMuscle: string
  muscleHead: MuscleKey
  equipment: Equipment
  exerciseType: ExerciseType
  movementPattern: MovementPattern
  difficulty: Difficulty
  isUnilateral: boolean
  defaultSets: number
  defaultReps: string
  tip: string
}

// ---------------------------------------------------------------------------
//  PUSH — klatka piersiowa, barki przednie/boczne, triceps
// ---------------------------------------------------------------------------

const PUSH_EXERCISES: ExerciseEntry[] = [

  // ===================== KLATKA GÓRNA (chest_upper) =====================

  {
    id: 'wyciskanie-sztangi-na-lawce-skosnej',
    name: 'Wyciskanie sztangi na ławce skośnej',
    aliases: ['incline bench press', 'incline barbell press', 'incline barbell bench press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '8-12',
    tip: 'Ławka 30-45°. Łopatki ściągnięte, sztanga nad obojczykami.',
  },
  {
    id: 'wyciskanie-hantli-na-lawce-skosnej',
    name: 'Wyciskanie hantli na ławce skośnej',
    aliases: ['incline dumbbell press', 'incline dumbbell bench press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '8-12',
    tip: 'Ławka 30-45°. Hantle nad linią obojczyków, łokcie 45° od tułowia.',
  },
  {
    id: 'wyciskanie-na-maszynie-na-skosie',
    name: 'Wyciskanie na maszynie na skosie',
    aliases: ['incline machine press', 'incline chest press machine'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Ustaw siedzisko tak, by uchwyty były na wysokości obojczyków.',
  },
  {
    id: 'rozpietki-hantlami-na-lawce-skosnej',
    name: 'Rozpiętki hantlami na ławce skośnej',
    aliases: ['incline dumbbell fly', 'incline dumbbell flyes', 'incline flyes'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Lekki łuk w łokciach. Rozciągaj do uczucia napięcia, nie bólu.',
  },
  {
    id: 'krzyzowanie-linek-dolne',
    name: 'Low cable crossover',
    aliases: ['krzyżowanie linek dolne', 'low cable crossover', 'low to high cable fly', 'cable crossover dolny'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Uchwyty z dołu do góry. Ruch po łuku, złącz ręce nad klatką.',
  },
  {
    id: 'pompki-z-nogami-na-podwyzszeniu',
    name: 'Pompki z nogami na podwyższeniu',
    aliases: ['decline push up', 'decline push-up', 'decline pushup', 'feet elevated push up'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_upper',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Stopy na ławce/skrzyni. Im wyżej nogi, tym więcej akcentu na górną klatkę.',
  },

  // ===================== KLATKA ŚRODKOWA (chest_middle) =====================

  {
    id: 'wyciskanie-sztangi-na-lawce-poziomej',
    name: 'Wyciskanie sztangi na ławce poziomej',
    aliases: ['bench press', 'flat bench press', 'barbell bench press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '6-10',
    tip: 'Łopatki ściągnij i wciśnij w ławkę. Stopy płasko na podłodze.',
  },
  {
    id: 'wyciskanie-hantli-na-lawce-poziomej',
    name: 'Wyciskanie hantli na ławce poziomej',
    aliases: ['dumbbell bench press', 'flat dumbbell press', 'dumbbell press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '8-12',
    tip: 'Większy zakres ruchu niż sztanga. Łokcie 45° od tułowia.',
  },
  {
    id: 'wyciskanie-na-maszynie',
    name: 'Wyciskanie na maszynie',
    aliases: ['chest press', 'machine chest press', 'chest press na maszynie'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Uchwyty na wysokości brodawek. Wyciskaj bez odchylania pleców.',
  },
  {
    id: 'pompki-klasyczne',
    name: 'Pompki klasyczne',
    aliases: ['push up', 'push-up', 'push ups', 'push-ups', 'pushup'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-20',
    tip: 'Ciało jak deska. Łokcie 45° od tułowia, klatka do podłogi.',
  },
  {
    id: 'rozpietki-hantlami-na-lawce-poziomej',
    name: 'Rozpiętki hantlami na ławce poziomej',
    aliases: ['dumbbell fly', 'dumbbell flyes', 'chest fly', 'chest flyes', 'flyes'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Lekki łuk w łokciach przez cały ruch. Czuj rozciągnięcie klatki.',
  },
  {
    id: 'rozpietki-na-maszynie',
    name: 'Rozpiętki na maszynie',
    aliases: ['pec deck', 'peck deck', 'butterfly', 'pec fly machine'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Złącz ramiona powoli przed klatką. 1-2s pauza w skurczu.',
  },
  {
    id: 'krzyzowanie-linek',
    name: 'Cable crossover',
    aliases: ['krzyżowanie linek', 'cable crossover', 'cable fly', 'cable flyes', 'cable chest fly'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_middle',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Lekki wychył tułowia. Krzyżuj ręce na dole dla pełnego skurczu.',
  },

  // ===================== KLATKA DOLNA (chest_lower) =====================

  {
    id: 'wyciskanie-sztangi-na-lawce-ujemnej',
    name: 'Wyciskanie sztangi na ławce ujemnej',
    aliases: ['decline bench press', 'decline barbell press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_lower',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Ławka ujemna 15-30°. Sztanga na dolną część klatki.',
  },
  {
    id: 'wyciskanie-hantli-na-lawce-ujemnej',
    name: 'Wyciskanie hantli na ławce ujemnej',
    aliases: ['decline dumbbell press', 'decline dumbbell bench press'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_lower',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Kontroluj hantle — na ławce ujemnej trudniej stabilizować.',
  },
  {
    id: 'pompki-na-poreczach',
    name: 'Dips',
    aliases: ['pompki na poręczach', 'dips', 'chest dips', 'parallel bar dips'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_lower',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Wychyl tułów do przodu dla akcentu na klatkę. Łokcie lekko na boki.',
  },
  {
    id: 'krzyzowanie-linek-gorne',
    name: 'High cable crossover',
    aliases: ['krzyżowanie linek górne', 'high cable crossover', 'high to low cable fly', 'cable crossover górny'],
    primaryMuscle: 'chest',
    muscleHead: 'chest_lower',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Uchwyty z góry na dół. Złącz ręce na poziomie bioder.',
  },

  // ===================== BARKI PRZEDNIE (shoulder_front) =====================

  {
    id: 'wyciskanie-sztangi-nad-glowe',
    name: 'Wyciskanie sztangi nad głowę',
    aliases: ['overhead press', 'ohp', 'military press', 'wyciskanie żołnierskie', 'standing barbell press', 'barbell overhead press'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '6-10',
    tip: 'Napnij pośladki i brzuch. Głowa lekko do przodu gdy sztanga przechodzi.',
  },
  {
    id: 'wyciskanie-hantli-nad-glowe',
    name: 'Wyciskanie hantli nad głowę',
    aliases: ['dumbbell shoulder press', 'dumbbell overhead press', 'shoulder press', 'seated dumbbell press', 'seated shoulder press', 'seated dumbbell shoulder press', 'wyciskanie hantli siedząc'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '8-12',
    tip: 'Można stojąc lub siedząc (oparcie 85-90°). Wyciskaj hantle po łuku ku środkowi, łokcie pod hantlami.',
  },
  {
    id: 'wyciskanie-arnolda',
    name: 'Wyciskanie Arnolda',
    aliases: ['arnold press', 'arnold dumbbell press'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Start z dłońmi do siebie. Obracaj podczas wyciskania — ruch płynny.',
  },
  {
    id: 'wyciskanie-nad-glowa-na-maszynie',
    name: 'Wyciskanie nad głowę na maszynie',
    aliases: ['machine shoulder press', 'shoulder press machine'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Siedzisko ustaw tak, by uchwyty startowały na wysokości uszu.',
  },
  {
    id: 'pike-push-up',
    name: 'Pike push-up',
    aliases: ['pike push up', 'pike push-up', 'pike pushup', 'pompki w pozycji pike', 'pompki w szczupaku'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '6-12',
    tip: 'Biodra wysoko (litera „V"), głowa schodzi między dłonie. Im wyżej stopy, tym trudniej.',
  },
  {
    id: 'wznosy-hantli-przodem',
    name: 'Wznosy hantli przodem',
    aliases: ['front raise', 'dumbbell front raise', 'front dumbbell raise', 'unoszenie hantli przodem', 'unoszenie ramion przodem', 'wznosy ramion przodem'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Unoś do poziomu oczu. Nie rozbujaj tułowiem — lekki ciężar.',
  },
  {
    id: 'wznosy-przodem-na-wyciagu',
    name: 'Wznosy przodem na wyciągu',
    aliases: ['cable front raise', 'front cable raise'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_front',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Stały opór wyciągu przez cały zakres. Unoś do poziomu barków.',
  },

  // ===================== BARKI BOCZNE (shoulder_side) =====================

  {
    id: 'wznosy-hantli-bokiem',
    name: 'Wznosy hantli bokiem',
    aliases: ['lateral raise', 'dumbbell lateral raise', 'side lateral raise', 'side raise', 'wznosy hantlami bokiem', 'wznosy bokiem z hantlami', 'wznosy bokiem', 'wznosy hantli bokiem stojąc', 'unoszenie ramion bokiem', 'unoszenie hantli bokiem'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_side',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Unoś do poziomu barków. Lekki łuk w łokciach, małe palce wyżej.',
  },
  {
    id: 'wznosy-hantli-bokiem-siedzac',
    name: 'Wznosy hantli bokiem siedząc',
    aliases: ['seated lateral raise', 'seated dumbbell lateral raise'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_side',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Siedzenie eliminuje rozpęd. Skup się na kontrolowanym ruchu.',
  },
  {
    id: 'wznosy-bokiem-na-wyciagu',
    name: 'Wznosy bokiem na wyciągu',
    aliases: ['cable lateral raise', 'single arm cable lateral raise'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_side',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'intermediate',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Wyciąg za plecami lub z boku. Stały opór przez cały zakres ruchu.',
  },
  {
    id: 'wznosy-bokiem-na-maszynie',
    name: 'Wznosy bokiem na maszynie',
    aliases: ['machine lateral raise', 'lateral raise machine', 'lateral raise na maszynie'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_side',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Maszyna stabilizuje tor — skup się na skurczu barków bocznych.',
  },
  {
    id: 'wioslowanie-sztangi-pod-brode',
    name: 'Wiosłowanie sztangi pod brodę',
    aliases: ['upright row', 'barbell upright row'],
    primaryMuscle: 'shoulders',
    muscleHead: 'shoulder_side',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'vertical_pull',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Szeroki chwyt dla barków bocznych. Ciągnij łokcie w górę, nie nadgarstki.',
  },

  // ===================== TRICEPS — GŁOWA DŁUGA (triceps_long) =====================

  {
    id: 'francuskie-wyciskanie-sztangi',
    name: 'Francuskie wyciskanie sztangi',
    aliases: ['skull crusher', 'skullcrusher', 'skull crushers', 'lying triceps extension', 'french press'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'sztanga',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Opuszczaj za głowę (nie na czoło) dla pełnego rozciągnięcia długiej głowy.',
  },
  {
    id: 'francuskie-wyciskanie-sztanga-ez',
    name: 'Francuskie wyciskanie ze sztangą EZ',
    aliases: ['ez bar skull crusher', 'ez bar french press', 'ez skull crusher'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'sztanga',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Sztanga EZ odciąża nadgarstki. Łokcie stale — ruch tylko w łokciach.',
  },
  {
    id: 'francuskie-wyciskanie-hantli',
    name: 'Francuskie wyciskanie hantli',
    aliases: ['dumbbell skull crusher', 'lying dumbbell triceps extension'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Neutralny chwyt hantli. Opuszczaj obok głowy, nie na twarz.',
  },
  {
    id: 'wyprosty-triceps-nad-glowa-na-wyciagu',
    name: 'Wyprosty triceps nad głowę na wyciągu',
    aliases: ['cable overhead triceps extension', 'overhead cable extension', 'overhead triceps extension'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Tyłem do wyciągu. Łokcie przy uszach, prostuj w pełni nad głową.',
  },
  {
    id: 'wyprosty-triceps-nad-glowa-z-hantla',
    name: 'Wyprosty triceps nad głowę z hantlą',
    aliases: ['overhead dumbbell triceps extension', 'dumbbell overhead extension', 'overhead tricep extension'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Chwyć hantlę oburącz za talerz. Opuszczaj za głowę, łokcie przy uszach.',
  },
  {
    id: 'wyprosty-triceps-nad-glowa-jednorecz',
    name: 'Wyprosty triceps nad głowę jednorącz',
    aliases: ['single arm overhead triceps extension', 'one arm dumbbell extension'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_long',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Drugą ręką stabilizuj łokieć. Pełne rozciągnięcie na dole.',
  },

  // ===================== TRICEPS — GŁOWA BOCZNA (triceps_lat) =====================

  {
    id: 'wyprosty-triceps-na-wyciagu',
    name: 'Wyprosty triceps na wyciągu',
    aliases: ['triceps pushdown', 'tricep pushdown', 'cable pushdown', 'pushdown', 'cable triceps pushdown', 'triceps na wyciągu', 'prostowanie ramion na wyciągu', 'prostowanie ramion', 'wyprost ramion', 'wyprosty ramion'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_lat',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Łokcie przyklejone do tułowia. Prostuj w pełni na dole, 1s pauza.',
  },
  {
    id: 'pushdown-z-lina',
    name: 'Pushdown z liną',
    aliases: ['rope pushdown', 'triceps rope pushdown', 'rope triceps pushdown'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_lat',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Rozciągaj linę na dole — rozsuń końce na boki dla pełnego skurczu.',
  },
  {
    id: 'wyprosty-triceps-na-wyciagu-jednorecz',
    name: 'Wyprosty triceps na wyciągu jednorącz',
    aliases: ['single arm pushdown', 'one arm cable pushdown', 'single arm triceps pushdown'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_lat',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Pozwala wyczuć pracę tricepsu każdą ręką osobno. Pełne wyprostowanie.',
  },
  {
    id: 'wyprosty-hantla-w-opadzie',
    name: 'Wyprosty hantla w opadzie',
    aliases: ['tricep kickback', 'kickback', 'dumbbell kickback', 'triceps kickback'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_lat',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Tułów równolegle do podłogi. Ramię nieruchomo — ruch tylko w łokciu.',
  },
  {
    id: 'wyprosty-triceps-na-maszynie',
    name: 'Wyprosty triceps na maszynie',
    aliases: ['triceps extension machine', 'machine triceps extension', 'seated triceps machine', 'triceps na maszynie', 'prostowanie ramion na maszynie'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_lat',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Łokcie na padzie. Prostuj w pełni, kontroluj powrót — stały tor maszyny.',
  },

  // ===================== TRICEPS — GŁOWA PRZYŚRODKOWA (triceps_med) =====================

  {
    id: 'wyciskanie-waskim-chwytem',
    name: 'Wyciskanie wąskim chwytem',
    aliases: ['close grip bench press', 'close grip press', 'narrow grip bench press'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_med',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Chwyt na szerokość barków. Łokcie blisko tułowia, nie rozchylaj.',
  },
  {
    id: 'pompki-diamentowe',
    name: 'Pompki diamentowe',
    aliases: ['diamond push up', 'diamond push-up', 'diamond pushup', 'close grip push up'],
    primaryMuscle: 'triceps',
    muscleHead: 'triceps_med',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-15',
    tip: 'Dłonie złączone w diament pod klatką. Łokcie przy tułowiu.',
  },
]

// ---------------------------------------------------------------------------
//  PULL — plecy, barki tylne, biceps, przedramiona
// ---------------------------------------------------------------------------

const PULL_EXERCISES: ExerciseEntry[] = [

  // ===================== PLECY SZEROKIE (back_lats) =====================


  {
    id: 'podciaganie',
    name: 'Podciąganie',
    aliases: ['pull up', 'pull-up', 'pull ups', 'pull-ups', 'podciąganie nachwytem', 'podciąganie szerokim chwytem', 'podciąganie z obciążeniem'],
    primaryMuscle: 'back',
    muscleHead: 'back_lats',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'vertical_pull',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '6-12',
    tip: 'Chwyt nachwytem szerzej niż barki. Ciągnij łokciami w dół, klatka do drążka.',
  },
  {
    id: 'podciaganie-podchwytem',
    name: 'Podciąganie podchwytem',
    aliases: ['chin up', 'chin-up', 'chin ups', 'chin-ups', 'podciąganie wąskim podchwytem', 'podciąganie podchwytem wąskim'],
    primaryMuscle: 'back',
    muscleHead: 'back_lats',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'vertical_pull',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '6-12',
    tip: 'Chwyt podchwytem na szerokość barków. Mocniej angażuje biceps niż nachwyt.',
  },
  {
    id: 'podciaganie-na-maszynie',
    name: 'Podciąganie na maszynie (grawitron)',
    aliases: ['assisted pull up', 'assisted pull-up', 'assisted pullup', 'grawitron', 'gravitron', 'assisted pull up machine', 'podciąganie asystowane', 'podciąganie wspomagane'],
    primaryMuscle: 'back',
    muscleHead: 'back_lats',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'vertical_pull',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Kolana/stopy na padzie kontrują ciężar ciała. Zmniejszaj wspomaganie, gdy rośnie siła.',
  },
  {
    id: 'sciaganie-drazka-wyciagu-gornego',
    name: 'Ściąganie drążka wyciągu górnego',
    aliases: ['lat pulldown', 'wide grip lat pulldown', 'wide grip pulldown'],
    primaryMuscle: 'back',
    muscleHead: 'back_lats',
    equipment: 'wyciąg',
    exerciseType: 'compound',
    movementPattern: 'vertical_pull',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Ciągnij drążek do górnej części klatki. Łopatki razem na dole ruchu.',
  },
  {
    id: 'sciaganie-drazka-podchwytem',
    name: 'Ściąganie drążka podchwytem',
    aliases: ['close grip lat pulldown', 'underhand lat pulldown', 'reverse grip pulldown'],
    primaryMuscle: 'back',
    muscleHead: 'back_lats',
    equipment: 'wyciąg',
    exerciseType: 'compound',
    movementPattern: 'vertical_pull',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Podchwyt wąski — więcej bicepsu. Kontroluj fazę negatywną.',
  },
  {
    id: 'sciaganie-drazka-na-prostych-ramionach',
    name: 'Ściąganie drążka na prostych ramionach',
    aliases: ['straight arm pulldown', 'straight arm lat pulldown', 'cable pullover', 'cable straight arm pullover', 'pullover na wyciągu'],
    primaryMuscle: 'back',
    muscleHead: 'back_lats',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'vertical_pull',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Ramiona proste przez cały ruch. Ciągnij drążek do ud łukiem, czuj rozciągnięcie latsów.',
  },
  {
    id: 'pullover-z-hantla',
    name: 'Pullover z hantlą',
    aliases: ['dumbbell pullover', 'pullover'],
    primaryMuscle: 'back',
    muscleHead: 'back_lats',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'vertical_pull',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Leż w poprzek ławki. Opuszczaj hantlę za głowę z łukiem w łokciach.',
  },

  // ===================== PLECY ŚRODKOWE (back_middle) =====================

  {
    id: 'wioslowanie-australijskie',
    name: 'Wiosłowanie australijskie',
    aliases: ['inverted row', 'australian pull-up', 'australian pull up', 'body row', 'wiosłowanie w podporze', 'podciąganie australijskie'],
    primaryMuscle: 'back',
    muscleHead: 'back_middle',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-15',
    tip: 'Ciało w linii prostej pod drążkiem/TRX. Ciągnij klatkę do drążka, łopatki razem.',
  },
  {
    id: 'wioslowanie-sztanga-w-opadzie',
    name: 'Wiosłowanie sztangą w opadzie',
    aliases: ['barbell row', 'bent over row', 'bent over barbell row'],
    primaryMuscle: 'back',
    muscleHead: 'back_middle',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_pull',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '8-12',
    tip: 'Tułów 45° do podłogi. Ciągnij sztangę do pępka, łopatki razem.',
  },
  {
    id: 'wioslowanie-hantla',
    name: 'Wiosłowanie hantla jedną ręką',
    aliases: ['dumbbell row', 'one arm dumbbell row', 'single arm dumbbell row'],
    primaryMuscle: 'back',
    muscleHead: 'back_middle',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Oprzyj kolano i dłoń na ławce. Ciągnij łokieć do biodra.',
  },
  {
    id: 'wioslowanie-pendlay',
    name: 'Wiosłowanie Pendlay',
    aliases: ['pendlay row', 'strict barbell row'],
    primaryMuscle: 'back',
    muscleHead: 'back_middle',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_pull',
    difficulty: 'advanced',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '6-8',
    tip: 'Tułów równolegle do podłogi. Sztanga startuje z podłogi każdy rep.',
  },
  {
    id: 'wioslowanie-na-wyciagu-siedzac',
    name: 'Wiosłowanie na wyciągu siedząc',
    aliases: ['seated cable row', 'seated row', 'cable row'],
    primaryMuscle: 'back',
    muscleHead: 'back_middle',
    equipment: 'wyciąg',
    exerciseType: 'compound',
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Klatka do przodu, nie odchylaj się. Ciągnij do brzucha, łopatki razem.',
  },
  {
    id: 'wioslowanie-t-bar',
    name: 'Wiosłowanie T-bar',
    aliases: ['t-bar row', 't bar row', 'landmine row'],
    primaryMuscle: 'back',
    muscleHead: 'back_middle',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'horizontal_pull',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Neutralny chwyt. Ciągnij do klatki, ściskaj łopatki na górze.',
  },
  {
    id: 'wioslowanie-na-maszynie',
    name: 'Wiosłowanie na maszynie',
    aliases: ['machine row', 'seated machine row', 'chest supported machine row'],
    primaryMuscle: 'back',
    muscleHead: 'back_middle',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Klatka oparta o pad. Skup się na ściskaniu łopatek na końcu ruchu.',
  },
  {
    id: 'wioslowanie-z-podparciem-klatki',
    name: 'Wiosłowanie z podparciem klatki',
    aliases: ['chest supported row', 'seal row', 'incline dumbbell row'],
    primaryMuscle: 'back',
    muscleHead: 'back_middle',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Ławka skośna, klatką na oparciu. Eliminuje oszukiwanie tułowiem.',
  },

  // ===================== PLECY GÓRNE — KAPTUROWY (back_upper) =====================

  {
    id: 'wzruszenia-sztanga',
    name: 'Wzruszenia sztangą',
    aliases: ['barbell shrugs', 'shrugs', 'barbell shrug'],
    primaryMuscle: 'back',
    muscleHead: 'back_upper',
    equipment: 'sztanga',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Barki prosto do góry (nie kręć). 1-2s pauza na górze.',
  },
  {
    id: 'wzruszenia-hantlami',
    name: 'Wzruszenia hantlami',
    aliases: ['dumbbell shrugs', 'dumbbell shrug'],
    primaryMuscle: 'back',
    muscleHead: 'back_upper',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Hantle po bokach. Wzruszaj barkami prosto do góry, pauza na szczycie.',
  },
  {
    id: 'wzruszenia-na-suwnicy',
    name: 'Wzruszenia na suwnicy',
    aliases: ['smith machine shrug', 'smith shrug', 'machine shrug', 'wzruszenia na maszynie', 'wzruszenia barków na maszynie', 'shrug na suwnicy'],
    primaryMuscle: 'back',
    muscleHead: 'back_upper',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Gryf suwnicy prowadzi ruch pionowo. Barki prosto do góry, pauza na szczycie.',
  },

  // ===================== PLECY DOLNE — PROSTOWNIKI (back_lower) =====================

  {
    id: 'martwy-ciag-klasyczny',
    name: 'Martwy ciąg klasyczny',
    aliases: ['deadlift', 'conventional deadlift', 'barbell deadlift'],
    primaryMuscle: 'back',
    muscleHead: 'back_lower',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'hinge',
    difficulty: 'advanced',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '5-8',
    tip: 'Plecy proste, sztanga przy ciele. Ciągnij biodra do przodu, nie plecami.',
  },
  {
    id: 'martwy-ciag-rumunski',
    name: 'Martwy ciąg rumuński',
    aliases: ['romanian deadlift', 'rdl', 'barbell rdl', 'rumuński martwy ciąg'],
    primaryMuscle: 'back',
    muscleHead: 'back_lower',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Nogi lekko ugięte. Opuszczaj sztangę wzdłuż ud, czuj rozciągnięcie.',
  },
  {
    id: 'martwy-ciag-rumunski-hantle',
    name: 'Martwy ciąg rumuński z hantlami',
    aliases: ['dumbbell romanian deadlift', 'dumbbell rdl'],
    primaryMuscle: 'back',
    muscleHead: 'back_lower',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Hantle wzdłuż ud. Większy zakres ruchu niż sztanga.',
  },
  {
    id: 'martwy-ciag-sumo',
    name: 'Martwy ciąg sumo',
    aliases: ['sumo deadlift', 'sumo barbell deadlift'],
    primaryMuscle: 'back',
    muscleHead: 'back_lower',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'hinge',
    difficulty: 'advanced',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '5-8',
    tip: 'Szeroka postawa, stopy na zewnątrz. Tułów bardziej pionowo niż klasyczny.',
  },
  {
    id: 'wyprosty-na-lawce-rzymskiej',
    name: 'Wyprosty na ławce rzymskiej',
    aliases: ['back extension', 'hyperextension', 'roman chair extension', 'wyprosty pleców', 'prostowanie pleców'],
    primaryMuscle: 'back',
    muscleHead: 'back_lower',
    equipment: 'własna_waga',
    exerciseType: 'isolation',
    movementPattern: 'hinge',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Kontrolowany ruch. Unoś tułów do linii prostej, nie przeprost.',
  },
  {
    id: 'prostowniki-grzbietu-na-maszynie',
    name: 'Prostowniki grzbietu na maszynie',
    aliases: ['back extension machine', 'machine back extension', 'lumbar extension machine', 'prostowanie tułowia na maszynie', 'wyprosty grzbietu na maszynie'],
    primaryMuscle: 'back',
    muscleHead: 'back_lower',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'hinge',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Plecy oparte o pad. Prostuj tułów płynnie, nie przeprostuj — kontrolowany powrót.',
  },

  // ===================== BARKI TYLNE (shoulder_rear) =====================

  {
    id: 'wznosy-hantli-w-opadzie',
    name: 'Wznosy hantli w opadzie',
    aliases: ['rear delt fly', 'bent over dumbbell fly', 'bent over reverse fly'],
    primaryMuscle: 'rear_shoulders',
    muscleHead: 'shoulder_rear',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Tułów równolegle do podłogi. Unoś hantle na boki, łopatki razem.',
  },
  {
    id: 'odwrotne-rozpietki-na-maszynie',
    name: 'Odwrotne rozpiętki na maszynie',
    aliases: ['reverse pec deck', 'rear delt machine', 'reverse fly machine'],
    primaryMuscle: 'rear_shoulders',
    muscleHead: 'shoulder_rear',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Twarzą do maszyny. Odwodź ramiona do tyłu, 1-2s pauza w skurczu.',
  },
  {
    id: 'face-pull',
    name: 'Face pull',
    aliases: ['face pulls', 'cable face pull', 'rope face pull'],
    primaryMuscle: 'rear_shoulders',
    muscleHead: 'shoulder_rear',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '15-20',
    tip: 'Ciągnij linę do twarzy, łokcie wysoko. Rotacja zewnętrzna na końcu.',
  },
  {
    id: 'odwrotne-rozpietki-na-wyciagu',
    name: 'Odwrotne rozpiętki na wyciągu',
    aliases: ['cable reverse fly', 'reverse cable fly', 'rear delt cable fly'],
    primaryMuscle: 'rear_shoulders',
    muscleHead: 'shoulder_rear',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'shoulder_isolation',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Skrzyżowane wyciągi. Odwodź ramiona na boki bez chwytu — za uchwyty.',
  },

  // ===================== BICEPS — GŁOWA DŁUGA (biceps_long) =====================

  {
    id: 'uginanie-na-modlitewniku',
    name: 'Uginanie na modlitewniku',
    aliases: ['preacher curl', 'scott curl', 'ez preacher curl'],
    primaryMuscle: 'biceps',
    muscleHead: 'biceps_short',
    equipment: 'sztanga',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Ramiona na padzie. Opuszczaj powoli — pełne wyprostowanie na dole.',
  },
  {
    id: 'uginanie-hantli-na-lawce-skosnej',
    name: 'Uginanie hantli na ławce skośnej',
    aliases: ['incline dumbbell curl', 'incline curl', 'incline bicep curl'],
    primaryMuscle: 'biceps',
    muscleHead: 'biceps_long',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Ławka 45°. Ramiona zwisają — rozciągnięcie długiej głowy bicepsu.',
  },
  {
    id: 'uginanie-koncentryczne',
    name: 'Uginanie koncentryczne',
    aliases: ['concentration curl', 'seated concentration curl'],
    primaryMuscle: 'biceps',
    muscleHead: 'biceps_long',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Łokieć oparty o udo. Pełny skurcz na górze, pauza 1s.',
  },
  {
    id: 'spider-curl',
    name: 'Spider curl',
    aliases: ['spider curl', 'prone incline curl'],
    primaryMuscle: 'biceps',
    muscleHead: 'biceps_short',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Klatką na skośnej ławce. Ramiona zwisają pionowo — zero oszukiwania.',
  },

  // ===================== BICEPS — GŁOWA KRÓTKA (biceps_short) =====================

  {
    id: 'uginanie-ramion-ze-sztanga',
    name: 'Uginanie ramion ze sztangą',
    aliases: ['barbell curl', 'standing barbell curl', 'bicep curl barbell'],
    primaryMuscle: 'biceps',
    muscleHead: 'biceps_short',
    equipment: 'sztanga',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Łokcie przy tułowiu. Nie rozbujaj — kontrolowany ruch.',
  },
  {
    id: 'uginanie-ze-sztanga-ez',
    name: 'Uginanie ze sztangą EZ',
    aliases: ['ez bar curl', 'ez curl', 'ez barbell curl'],
    primaryMuscle: 'biceps',
    muscleHead: 'biceps_short',
    equipment: 'sztanga',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Gryf EZ odciąża nadgarstki. Chwyt szerszy akcentuje głowę krótką.',
  },
  {
    id: 'uginanie-ramion-z-hantlami',
    name: 'Uginanie ramion z hantlami',
    aliases: ['dumbbell curl', 'bicep curl', 'biceps curl', 'dumbbell bicep curl', 'standing dumbbell curl'],
    primaryMuscle: 'biceps',
    muscleHead: 'biceps_short',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Supinuj nadgarstek podczas unoszenia. Na górze mały palec wyżej.',
  },
  {
    id: 'uginanie-ramion-na-wyciagu',
    name: 'Uginanie ramion na wyciągu',
    aliases: ['cable curl', 'cable bicep curl', 'standing cable curl'],
    primaryMuscle: 'biceps',
    muscleHead: 'biceps_short',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Stały opór wyciągu. Łokcie nieruchomo przy tułowiu.',
  },
  {
    id: 'uginanie-ramion-na-maszynie',
    name: 'Uginanie ramion na maszynie',
    aliases: ['machine biceps curl', 'machine curl', 'seated biceps machine', 'biceps na maszynie', 'uginanie na maszynie'],
    primaryMuscle: 'biceps',
    muscleHead: 'biceps_short',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Ramiona na padzie eliminują oszukiwanie. Pełne uginanie, kontrolowany powrót.',
  },

  // ===================== BRACHIALIS (biceps_brach) =====================

  {
    id: 'uginanie-hantli-mlotkowo',
    name: 'Hammer curl',
    aliases: ['uginanie hantli młotkowo', 'hammer curl', 'hammer curls', 'dumbbell hammer curl'],
    primaryMuscle: 'biceps',
    muscleHead: 'biceps_brach',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Chwyt neutralny (kciuki do góry). Buduje brachialis i przedramiona.',
  },
  {
    id: 'uginanie-mlotkowo-na-wyciagu',
    name: 'Uginanie młotkowo na wyciągu z liną',
    aliases: ['rope hammer curl', 'cable hammer curl', 'cable rope curl'],
    primaryMuscle: 'biceps',
    muscleHead: 'biceps_brach',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Lina wymusza chwyt neutralny. Stały opór przez cały zakres.',
  },

  // ===================== PRZEDRAMIONA (forearms) =====================

  {
    id: 'uginanie-zottmana',
    name: 'Uginanie Zottmana',
    aliases: ['zottman curl', 'zottman curls'],
    primaryMuscle: 'forearms',
    muscleHead: 'forearms',
    equipment: 'hantle',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Uginaj supinując, opuszczaj pronując. Łączy biceps + przedramiona.',
  },
  {
    id: 'uginanie-nadgarstkow-ze-sztanga',
    name: 'Uginanie nadgarstków ze sztangą',
    aliases: ['wrist curl', 'barbell wrist curl', 'forearm curl'],
    primaryMuscle: 'forearms',
    muscleHead: 'forearms',
    equipment: 'sztanga',
    exerciseType: 'isolation',
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '15-20',
    tip: 'Przedramiona na kolanach, nadgarstki poza kolanami. Pełny zakres.',
  },
]

// ---------------------------------------------------------------------------
//  LEGS — czworogłowy uda, dwugłowy uda, pośladki, przywodziciele, łydki, core
// ---------------------------------------------------------------------------

const LEGS_EXERCISES: ExerciseEntry[] = [

  // ===================== CZWOROGŁOWY UDA (quads) =====================

  {
    id: 'przysiad-ze-sztanga',
    name: 'Przysiad ze sztangą',
    aliases: ['squat', 'back squat', 'barbell squat', 'barbell back squat'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'squat',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '6-10',
    tip: 'Sztanga wysoko na trapezach. Kolana w linii palców, głębokość poniżej równoległej.',
  },
  {
    id: 'przysiad-przedni',
    name: 'Przysiad przedni',
    aliases: ['front squat', 'barbell front squat'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'squat',
    difficulty: 'advanced',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '6-10',
    tip: 'Łokcie wysoko, sztanga na przednich deltoidach. Tułów bardziej pionowo.',
  },
  {
    id: 'przysiad-z-hantlem',
    name: 'Przysiad z hantlem',
    aliases: ['goblet squat', 'dumbbell goblet squat'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'squat',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Hantle przy klatce. Świetne na naukę techniki przysiadu.',
  },
  {
    id: 'hack-squat',
    name: 'Hack squat',
    aliases: ['hack squat', 'machine hack squat'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'squat',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Plecy płasko na oparciu. Stopy nisko = więcej quadsów.',
  },
  {
    id: 'przysiad-na-suwnicy',
    name: 'Przysiad na suwnicy',
    aliases: ['smith machine squat', 'smith squat'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'squat',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Stopy lekko przed siebie. Prowadnica stabilizuje tor — skup się na głębokości.',
  },
  {
    id: 'wyciskanie-nogami',
    name: 'Leg press',
    aliases: ['wyciskanie nogami', 'leg press', 'machine leg press', '45 degree leg press'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'squat',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Stopy na środku platformy. Nie blokuj kolan na górze, dolna część pleców na oparciu.',
  },
  {
    id: 'przysiad-bulgarski',
    name: 'Przysiad bułgarski',
    aliases: ['bulgarian split squat', 'split squat', 'rear foot elevated split squat', 'bułgarski przysiad'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'lunge',
    difficulty: 'intermediate',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Tylna stopa na ławce. Tułów pionowo, kolano do podłogi.',
  },
  {
    id: 'przysiad-masa-ciala',
    name: 'Przysiad z masą ciała',
    aliases: ['bodyweight squat', 'air squat', 'przysiad bez obciążenia', 'przysiad z masą ciała', 'przysiady', 'przysiad wolny'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'squat',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '15-25',
    tip: 'Stopy na szerokość barków, zejdź poniżej równoległej. Pięty przyklejone do podłogi.',
  },
  {
    id: 'wykroki-masa-ciala',
    name: 'Wykroki',
    aliases: ['bodyweight lunge', 'wykroki bez obciążenia', 'wykroki z masą ciała', 'wykroki w miejscu'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'lunge',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Długi krok, kolano tylnej nogi prawie dotyka podłogi. Tułów pionowo.',
  },
  {
    id: 'wykroki-z-hantlami',
    name: 'Wykroki z hantlami',
    aliases: ['dumbbell lunge', 'dumbbell lunges', 'lunge', 'lunges', 'reverse lunge', 'reverse lunges'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'lunge',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Długi krok. Kolano tylnej nogi prawie dotyka podłogi.',
  },
  {
    id: 'wykroki-ze-sztanga',
    name: 'Wykroki ze sztangą',
    aliases: ['barbell lunge', 'barbell lunges'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'lunge',
    difficulty: 'intermediate',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Sztanga na trapezach jak w przysiadzie. Wymaga dobrej równowagi.',
  },
  {
    id: 'wykroki-chodzace',
    name: 'Wykroki chodzące',
    aliases: ['walking lunge', 'walking lunges'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'lunge',
    difficulty: 'intermediate',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Płynne przejście z kroku w krok. Tułów pionowo, nie kiwaj się.',
  },
  {
    id: 'wchodzenie-na-skrzynie',
    name: 'Wchodzenie na skrzynię',
    aliases: ['step up', 'step-up', 'dumbbell step up'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'lunge',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Cały ciężar na nodze górnej. Nie odpychaj się dolną stopą.',
  },
  {
    id: 'wyprosty-nog',
    name: 'Wyprosty nóg',
    aliases: ['leg extension', 'leg extensions', 'machine leg extension', 'prostowanie nóg'],
    primaryMuscle: 'quads',
    muscleHead: 'quads',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'squat',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Pełne wyprostowanie na górze, 1-2s pauza. Kontroluj negatyw.',
  },

  // ===================== DWUGŁOWY UDA (hamstrings) =====================

  {
    id: 'uginanie-nog-lezac',
    name: 'Uginanie nóg leżąc',
    aliases: ['lying leg curl', 'prone leg curl', 'hamstring curl'],
    primaryMuscle: 'hamstrings',
    muscleHead: 'hamstrings',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'hinge',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Biodra na padzie. Zginaj do pełna, kontroluj fazę negatywną.',
  },
  {
    id: 'uginanie-nog-siedzac',
    name: 'Uginanie nóg siedząc',
    aliases: ['seated leg curl', 'seated hamstring curl'],
    primaryMuscle: 'hamstrings',
    muscleHead: 'hamstrings',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'hinge',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Lepsze rozciągnięcie hamstringów niż leżąc. Pełny zakres ruchu.',
  },
  {
    id: 'nordic-curl',
    name: 'Nordic curl',
    aliases: ['nordic curl', 'nordic hamstring curl', 'nordic ham curl'],
    primaryMuscle: 'hamstrings',
    muscleHead: 'hamstrings',
    equipment: 'własna_waga',
    exerciseType: 'isolation',
    movementPattern: 'hinge',
    difficulty: 'advanced',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '5-8',
    tip: 'Kolana na podłodze, stopy zablokowane. Opuszczaj się powoli jak najniżej.',
  },
  {
    id: 'glute-ham-raise',
    name: 'Glute ham raise',
    aliases: ['glute ham raise', 'ghr', 'glute-ham raise'],
    primaryMuscle: 'hamstrings',
    muscleHead: 'hamstrings',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'hinge',
    difficulty: 'advanced',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '6-10',
    tip: 'Na ławce GHR. Pracują hamstringi i pośladki jednocześnie.',
  },

  // ===================== POŚLADKI (glutes) =====================

  {
    id: 'wypychanie-bioder',
    name: 'Hip thrust',
    aliases: ['wypychanie bioder', 'barbell hip thrust', 'hip thrusty'],
    primaryMuscle: 'glutes',
    muscleHead: 'glutes',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '8-12',
    tip: 'Łopatki na ławce. Pełne wypchnięcie bioder, ściskaj pośladki na górze.',
  },
  {
    id: 'hip-thrust-na-maszynie',
    name: 'Hip thrust na maszynie',
    aliases: ['glute drive', 'glute drive machine', 'hip thrust machine', 'machine hip thrust', 'wypychanie bioder na maszynie'],
    primaryMuscle: 'glutes',
    muscleHead: 'glutes',
    equipment: 'maszyna',
    exerciseType: 'compound',
    movementPattern: 'hinge',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '10-12',
    tip: 'Pad na biodrach, plecy o oparcie. Pełne wypchnięcie, ściskaj pośladki 1-2s na górze.',
  },
  {
    id: 'most-biodrowy',
    name: 'Most biodrowy',
    aliases: ['glute bridge', 'bodyweight glute bridge'],
    primaryMuscle: 'glutes',
    muscleHead: 'glutes',
    equipment: 'własna_waga',
    exerciseType: 'compound',
    movementPattern: 'hinge',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Plecy na podłodze. Unoś biodra, ściskaj pośladki 2s na górze.',
  },
  {
    id: 'most-biodrowy-ze-sztanga',
    name: 'Most biodrowy ze sztangą',
    aliases: ['barbell glute bridge', 'weighted glute bridge'],
    primaryMuscle: 'glutes',
    muscleHead: 'glutes',
    equipment: 'sztanga',
    exerciseType: 'compound',
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Sztanga na biodrach z padem. Pełne wypchnięcie bioder.',
  },
  {
    id: 'odwodzenie-nog-na-maszynie',
    name: 'Odwodzenie nóg na maszynie',
    aliases: ['hip abduction', 'hip abduction machine', 'abductor machine'],
    primaryMuscle: 'glutes',
    muscleHead: 'glutes',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'hinge',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Odwodź kolana na boki. Pauza 1-2s w pełnym rozwarciu.',
  },
  {
    id: 'odwodzenie-nogi-na-wyciagu',
    name: 'Odwodzenie nogi na wyciągu',
    aliases: ['cable kickback', 'cable glute kickback', 'cable hip extension'],
    primaryMuscle: 'glutes',
    muscleHead: 'glutes',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'hinge',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Mankiet na kostkę. Odwodź nogę do tyłu, ściskaj pośladek na końcu.',
  },

  // ===================== PRZYWODZICIELE (adductors) =====================

  {
    id: 'przywodzenie-nog-na-maszynie',
    name: 'Przywodzenie nóg na maszynie',
    aliases: ['hip adduction', 'hip adduction machine', 'adductor machine'],
    primaryMuscle: 'adductors',
    muscleHead: 'adductors',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'squat',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Przywodź kolana do siebie. Kontrolowany ruch, pauza w skurczu.',
  },
  {
    id: 'przysiad-sumo-z-hantlem',
    name: 'Przysiad sumo z hantlem',
    aliases: ['sumo squat', 'dumbbell sumo squat', 'plie squat'],
    primaryMuscle: 'quads',
    muscleHead: 'adductors',
    equipment: 'hantle',
    exerciseType: 'compound',
    movementPattern: 'squat',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-12',
    tip: 'Szeroka postawa, stopy na zewnątrz 45°. Hantle między nogami.',
  },

  // ===================== ŁYDKI (calves) =====================

  {
    id: 'wspięcia-na-palce-stojac',
    name: 'Wspięcia na palce stojąc',
    aliases: ['standing calf raise', 'calf raise', 'machine calf raise'],
    primaryMuscle: 'calves',
    muscleHead: 'calves',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'calf',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '12-15',
    tip: 'Pełne rozciągnięcie na dole, pauza 1s na górze. Łydki lubią objętość.',
  },
  {
    id: 'wspięcia-na-palce-siedzac',
    name: 'Wspięcia na palce siedząc',
    aliases: ['seated calf raise', 'seated calf'],
    primaryMuscle: 'calves',
    muscleHead: 'calves',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'calf',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 4,
    defaultReps: '12-15',
    tip: 'Akcentuje mięsień płaszczkowaty. Pełny zakres ruchu.',
  },
  {
    id: 'wspięcia-na-palce-ze-sztanga',
    name: 'Wspięcia na palce ze sztangą',
    aliases: ['barbell calf raise', 'standing barbell calf raise'],
    primaryMuscle: 'calves',
    muscleHead: 'calves',
    equipment: 'sztanga',
    exerciseType: 'isolation',
    movementPattern: 'calf',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Sztanga na plecach, palce na podwyższeniu. Wymaga równowagi.',
  },
  {
    id: 'wspięcia-na-palce-na-leg-press',
    name: 'Wspięcia na palce na leg press',
    aliases: ['leg press calf raise', 'calf press'],
    primaryMuscle: 'calves',
    muscleHead: 'calves',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'calf',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Palce na dolnej krawędzi platformy. Nie blokuj kolan.',
  },
  {
    id: 'wspięcia-na-palce-jednonoz',
    name: 'Wspięcia na palce jednonóż',
    aliases: ['single leg calf raise', 'one leg calf raise'],
    primaryMuscle: 'calves',
    muscleHead: 'calves',
    equipment: 'własna_waga',
    exerciseType: 'isolation',
    movementPattern: 'calf',
    difficulty: 'beginner',
    isUnilateral: true,
    defaultSets: 3,
    defaultReps: '15-20',
    tip: 'Na krawędzi stopnia. Pełne rozciągnięcie i skurcz, trzymaj się ściany.',
  },

  // ===================== BRZUCH / CORE =====================

  {
    id: 'brzuszki',
    name: 'Brzuszki',
    aliases: ['crunch', 'crunches', 'ab crunch'],
    primaryMuscle: 'core',
    muscleHead: 'abs',
    equipment: 'własna_waga',
    exerciseType: 'isolation',
    movementPattern: 'core',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '15-20',
    tip: 'Odrywaj łopatki od podłogi. Nie ciągnij za szyję, ręce przy skroniach.',
  },
  {
    id: 'brzuszki-na-wyciagu',
    name: 'Brzuszki na wyciągu',
    aliases: ['cable crunch', 'cable crunches', 'kneeling cable crunch'],
    primaryMuscle: 'core',
    muscleHead: 'abs',
    equipment: 'wyciąg',
    exerciseType: 'isolation',
    movementPattern: 'core',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Na kolanach, lina za głową. Zwijaj tułów łokciami do kolan.',
  },
  {
    id: 'brzuszki-na-maszynie',
    name: 'Brzuszki na maszynie',
    aliases: ['ab crunch machine', 'machine crunch', 'abdominal machine', 'brzuszki na siedząco', 'maszyna do brzuszków'],
    primaryMuscle: 'core',
    muscleHead: 'abs',
    equipment: 'maszyna',
    exerciseType: 'isolation',
    movementPattern: 'core',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '12-15',
    tip: 'Zwijaj tułów mięśniami brzucha, nie ciągnij ramionami. Kontrolowany powrót.',
  },
  {
    id: 'unoszenie-nog-w-zwisie',
    name: 'Unoszenie nóg w zwisie',
    aliases: ['hanging leg raise', 'hanging knee raise', 'leg raise'],
    primaryMuscle: 'core',
    muscleHead: 'abs',
    equipment: 'własna_waga',
    exerciseType: 'isolation',
    movementPattern: 'core',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '10-15',
    tip: 'Wisz na drążku. Unoś nogi kontrolowanie, nie rozbujaj ciała.',
  },
  {
    id: 'skrety-rosyjskie',
    name: 'Skręty rosyjskie',
    aliases: ['russian twist', 'russian twists', 'seated russian twist'],
    primaryMuscle: 'core',
    muscleHead: 'obliques',
    equipment: 'własna_waga',
    exerciseType: 'isolation',
    movementPattern: 'core',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '15-20',
    tip: 'Siedząc, nogi uniesione. Obracaj tułów, dotykaj podłogi po obu stronach.',
  },
  {
    id: 'deska',
    name: 'Deska',
    aliases: ['plank', 'front plank', 'forearm plank'],
    primaryMuscle: 'core',
    muscleHead: 'core',
    equipment: 'własna_waga',
    exerciseType: 'isolation',
    movementPattern: 'core',
    difficulty: 'beginner',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '30-60s',
    tip: 'Ciało jak deska — napnij brzuch i pośladki. Nie wyginaj bioder.',
  },
  {
    id: 'ab-wheel-rollout',
    name: 'Ab wheel / Rollout',
    aliases: ['ab wheel', 'ab rollout', 'rollout', 'ab wheel rollout'],
    primaryMuscle: 'core',
    muscleHead: 'core',
    equipment: 'własna_waga',
    exerciseType: 'isolation',
    movementPattern: 'core',
    difficulty: 'intermediate',
    isUnilateral: false,
    defaultSets: 3,
    defaultReps: '8-12',
    tip: 'Na kolanach, wyjeżdżaj jak najdalej. Napnij brzuch, nie przeprostuj pleców.',
  },
]

// ---------------------------------------------------------------------------
//  Helpers
// ---------------------------------------------------------------------------

// Eksport pełnej listy — używany przez testy spójności (pokrycie exerciseDetails).
export const ALL_EXERCISES = [...PUSH_EXERCISES, ...PULL_EXERCISES, ...LEGS_EXERCISES]

const _byId = new Map<string, ExerciseEntry>()
const _byName = new Map<string, ExerciseEntry>()
const _byAlias = new Map<string, ExerciseEntry>()

for (const ex of ALL_EXERCISES) {
  _byId.set(ex.id, ex)
  _byName.set(ex.name.toLowerCase(), ex)
  for (const alias of ex.aliases) {
    _byAlias.set(alias.toLowerCase(), ex)
  }
}

export function findExerciseById(id: string): ExerciseEntry | undefined {
  return _byId.get(id)
}

export function findExerciseByName(name: string): ExerciseEntry | undefined {
  const lower = name.toLowerCase().trim()
  return _byName.get(lower) || _byAlias.get(lower)
}

export function getExercisesForMuscle(muscleHead: MuscleKey): ExerciseEntry[] {
  return ALL_EXERCISES.filter(e => e.muscleHead === muscleHead)
}

// Ćwiczenia dla zestawu głów mięśniowych (np. MUSCLE_HEADS_BY_TYPE z ai.ts),
// opcjonalnie zawężone do dostępnego sprzętu. Kolejność wg kolejności w bazie.
export function getExercisesForHeads(muscleHeads: string[], allowedEquipment?: Equipment[]): ExerciseEntry[] {
  return ALL_EXERCISES.filter(e =>
    muscleHeads.includes(e.muscleHead) &&
    (!allowedEquipment || allowedEquipment.includes(e.equipment))
  )
}

